//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gods.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gods.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function Route(url, key, obj) {
        ///	&quot;user strict&quot;;
        ///	var baseURL = &quot;&quot;;
        ///	function makeClass(n, i) {
        ///		var oi = n[i];
        ///		n[i] = function (data) {
        ///			for (var i in data || {}) {
        ///				this[i] = data[i];
        ///			}
        ///		};
        ///		oi.Methods.forEach(m=&gt; {
        ///			n[i].prototype[m.Name] = function () {
        ///				var method = arguments[0] instanceof HTMLFormElement,
        ///					data = null,
        ///					u = url;
        ///				if (method) {
        ///					method = &quot;post&quot;;
        ///					data = new FormData(arguments[0]);
        ///					data.append(key, m.Key);
        ///					for (var i in th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if (typeof AjaxRoute === &quot;function&quot;) {//HashCode//GetHashCode
        ///	AjaxRoute(&quot;/AjaxRoute&quot;, &quot;AjaxKey&quot;, Value);
        ///}
        ///function FillFunc(from, to) {
        ///	for (var i in from) {
        ///		var ti = to[i];
        ///		var fi = from[i];
        ///		if (typeof ti === &quot;function&quot;) {
        ///			if (typeof fi !== &quot;object&quot;) {
        ///				return;
        ///			}
        ///			if (i in ti.prototype) {
        ///				ti.prototype[i].Callback = fi;
        ///			}
        ///		} else if (typeof ti === &quot;object&quot;) {
        ///			if (typeof fi !== &quot;object&quot;) {
        ///				return;
        ///			}
        ///			FillFunc(fi, ti);
        ///		}
        ///	}
        ///}
        ///FillFunc(Namespace,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Map1 {
            get {
                return ResourceManager.GetString("Map1", resourceCulture);
            }
        }
    }
}
